# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-24 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercredentails',
            name='access_secret',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twittercredentails',
            name='access_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twittercredentails',
            name='consumer_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twittercredentails',
            name='consumer_secret',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
